name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Build KBALL3
        run: |
          west build -s zmk/app -b xiao_ble -- -DSHIELD=kball3 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cp build/zephyr/zmk.uf2 kball3.uf2

      - name: Build Settings Reset
        run: |
          rm -rf build
          west build -s zmk/app -b xiao_ble -- -DSHIELD=settings_reset -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cp build/zephyr/zmk.uf2 settings_reset.uf2

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kball3_firmware
          path: |
            kball3.uf2
            settings_reset.uf2
